#
language: r
sudo: required
warnings_are_errors: true
dist: trusty
cache: packages

addons:
  apt:
    packages:
      - python2.7

before_install:
  - pip install numpy 
  
env:
 global:
   - CRAN: http://cran.rstudio.com

r_packages:
   - reticulate
   - jsonlite

